### PR TITLE
getAttribute() & hasAttribute() & getProp()

### LINKED ISSUE #100: Problems with `hasAttr()`
Hi, I have been recently writing unit tests using avoriaz. There were a few problems with `hasAttr()`, for example:

```js
var wrapper = mount(VueComponent)
// I'd like to check if `wrapper` has an attribute called `some-attr`,
// and don't care about what its value is.
expect(wrapper.hasAttr('some-attr')).toBe(true)
// But avoriaz requries a second argument:
// => Error: wrapper.hasAttribute() must be passed value as a string
// If the attribute value is variable then `hasAttr()` is likely to be unusable.
```

Further more, `hasAttr()` is not ideal for error report:

```js
var wrapper = mount(VueComponent)
expect(wrapper.hasAttr('some-attr', 'some-value')).toBe(true)
// If the actual value is something other than expected,
// then the error message gives no idea about what actually happens:
// => Error: Expected false to be true.
```

I think it would make debugging much easier if the API looks like this:

```js
var wrapper = mount(VueComponent)
// Checks for existence of the attribute:
expect(wrapper.hasAttr('some-attr')).toBe(true) 
// Checks for value identity:
expect(wrapper.getAttr('some-attr')).toBe('some-value')
// If the actual value is not as expected, then the error message maybe look like this:
// => Error: Expected 'not-some-value' to be 'some-value'. 
```

### PR DESCRIPTION
**Pull request by riophae**
Closes #100. 
Added `getAttribute()` & `getProp()` methods and changed behavior of `hasAttribute()` method.

### CODE REVIEW

File: src/Wrapper.js [hunk 1]
```diff
@@ -133,22 +133,57 @@ export default class Wrapper implements WrapperInterface {
...
+    return this.element.getAttribute(attribute);
+  }
+
+  /**
+   * Returns prop value of a Vue instance
+   *
+   * @param {String} propName - prop name to assert
+   * @returns {*}
+   */
+  getProp(propName: string) {
```
Comment (riophae) [inline src/Wrapper.js]: I don't know whether I am doing right here...
Any suggestions are welcome!

Comment (eddyerburgh) [inline src/Wrapper.js]: Looks great!

**Comment by eddyerburgh** [comment]
Looks great, two more things are needed before merging - 

* docs - can you update the docs and add a page for `getAttribute` and `getProp`?
* types - this project has a typescript types definitions file - https://github.com/eddyerburgh/avoriaz/blob/master/types/index.d.ts . There is a typescript test file - types/test/mount - to check the functions can be used correctly

File: docs/api/mount/hasAttribute.md [hunk 2]
```diff
@@ -1,17 +1,14 @@
-# hasAttribute(attribute, value)
```
Comment (eddyerburgh) [inline docs/api/mount/hasAttribute.md]: Thinking about it, I think hasAttribute should take an optional value. If you can make the changes, please do. Otherwise I'm happy to change myself 😀

Comment (riophae) [inline docs/api/mount/hasAttribute.md]: Hummm... I think it's better to encourage people to use `getAttribute()` which is competent to do the same job and does it better :]

Comment (riophae) [inline docs/api/mount/hasAttribute.md]: Or for backward-compatibility reason, we can keep the old syntax as well...

Comment (eddyerburgh) [inline docs/api/mount/hasAttribute.md]: I agree, but people will need to change tests that rely on hasAttribute. 

We could just deprecate hasAttribute (remove it from docs, add a warning that it will be removed in later versions, but keep the same functionality)

Comment (riophae) [inline docs/api/mount/hasAttribute.md]: You're right.

**Comment by eddyerburgh** [comment]
Thanks for this PR. I'm going on vacation tomorrow for 1 week. I won't have my laptop with me, so I can merge the PR, but I won't be able to release unfortunately. 

Also, I'm proposing we add the same methods to vue-test-utils - you might be interested in the proposal - https://github.com/vuejs/vue-test-utils/issues/27

File: docs/api/mount/getProp.md [hunk 3]
```diff
@@ -0,0 +1,18 @@
+# propsData()
```
Comment (eddyerburgh) [inline docs/api/mount/getProp.md]: Can you change this to getProp please

File: docs/api/mount/getProp.md [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+Returns value of specified prop of Vue instances. Can only be called on a Vue component wrapper.
```
Comment (eddyerburgh) [inline docs/api/mount/getProp.md]: I think 

> Returns value of specified prop of Vue instances

 should be 

> Returns value of specified prop of Vue instance

File: docs/api/mount/hasAttribute.md (hunk 2 above)
Comment (eddyerburgh) [inline docs/api/mount/hasAttribute.md]: Can you update the PR to keep the hasAttribute functionality?

File: docs/api/mount/getProp.md (hunk 3 above)
Comment (riophae) [inline docs/api/mount/getProp.md]: Oh, I'm sorry for the mistakes!

File: docs/api/mount/hasAttribute.md (hunk 2 above)
Comment (riophae) [inline docs/api/mount/hasAttribute.md]: Yeah, I have done that a few days ago.

Comment (eddyerburgh) [inline docs/api/mount/hasAttribute.md]: Sorry, I meant to keep the hasAttribute docs as they were. At the moment details on value are being removed:

For example, `hasAttribute(attribute)` should be `hasAttribute(attribute, value)` and `Check if wrapper DOM node has specified attribute` should be `Check if wrapper DOM node has attribute matching value`

Comment (riophae) [inline docs/api/mount/hasAttribute.md]: Uhhh...I am a bit confused. You said remove hasAttribute from docs. Now we have deprecated the usage of `hasAttribute(attribute, value)`, and we should keep the detail on it?

Comment (eddyerburgh) [inline docs/api/mount/hasAttribute.md]: Ah yeah sorry @riophae , I forgot our past conversation. You're correct.

**Comment by eddyerburgh** [comment]
Hi, I can merge this soon. Can you fix the conflicts in types/index.d.ts?

**Comment by riophae** [comment]
@eddyerburgh done!

**Comment by eddyerburgh** [comment]
Great 🤗

I've released the changes as 4.0.0.

Thanks so much for the PR 🙂
